"""Adds users table

Revision ID: 0c9d485e6f48
Revises: 3f622babff4d
Create Date: 2020-04-18 22:45:42.706512

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0c9d485e6f48"
down_revision = "3f622babff4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("report_count", sa.Integer(), nullable=True),
        sa.Column("turnip_banned", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
