"""Adds user reports created count

Revision ID: 213503d71cdb
Revises: 0c9d485e6f48
Create Date: 2020-04-18 23:20:57.902267

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "213503d71cdb"
down_revision = "0c9d485e6f48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("reports_created_count", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "reports_created_count")
    # ### end Alembic commands ###
