"""adds turnip table

Revision ID: 3f622babff4d
Revises: e04fb668229b
Create Date: 2020-04-16 23:21:38.050394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f622babff4d'
down_revision = 'e04fb668229b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnips',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('guild_id', sa.BIGINT(), nullable=True),
    sa.Column('is_selling', sa.Boolean(), nullable=True),
    sa.Column('invite_key', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('open_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turnips')
    # ### end Alembic commands ###
