"""Add flower and airport to profiles table

Revision ID: 55854d087a67
Revises: fd5932ca6a7e
Create Date: 2020-07-18 16:10:58.874520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55854d087a67'
down_revision = 'fd5932ca6a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('airport', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('flower', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'flower')
    op.drop_column('profiles', 'airport')
    # ### end Alembic commands ###
