"""initial revision, adds Guild

Revision ID: e04fb668229b
Revises: 
Create Date: 2020-04-16 22:02:49.480390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04fb668229b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guilds')
    # ### end Alembic commands ###
