"""Add timezone, flower and airport to profiles table

Revision ID: fd5932ca6a7e
Revises: 4180bbfd1945
Create Date: 2020-07-18 16:09:31.258020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5932ca6a7e'
down_revision = '4180bbfd1945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('timezone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'timezone')
    # ### end Alembic commands ###
